" ===================== Vundle Setup ======================
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins to install
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" ===================== Vundle Setup End ======================

syn on
set smd
set hls
set backspace=indent,eol,start
set autoindent
set expandtab
set sw=4
set ts=4
set number

set background=dark
colorscheme solarized

" Airline plugin configuration
set laststatus=2
let g:airline_powerline_fonts=1
let g:airline_theme='solarized'
set t_Co=256


"map <C-T> :TlistToggle

au BufRead mutt-* set ft=mail
au BufRead mutt-* setlocal fo+=aw
