#!/bin/bash

#export OOO_FORCE_DESKTOP=gnome

xsetroot -cursor_name left_ptr

trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 9 --transparent true --tint 0x191970 --height 16 &

xset -b
#eval $(cat ~/.fehbg)

xscreensaver -no-splash &

stalonetray &
nm-applet &

~/.fehbg

exec /usr/bin/xmonad
